---
services:
  automatic1111:
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
              count: all
              driver: nvidia
    env_file:
      - path: a1111.env
        required: false
    image: ghcr.io/joepitt91/automatic1111:latest
    ports:
      - '127.0.0.1:7860:7860'
    pull_policy: always
    restart: unless-stopped
    volumes:
      - automatic1111:/data
volumes:
  automatic1111: null