# SPDX-FileCopyrightText: 2025 Joe Pitt
#
# SPDX-License-Identifier: GPL-3.0-only

name: Build Image for Specific Version
on:
  workflow_dispatch:
    inputs:
      version:
        description: The version to build, e.g. 1.10.1
        required: true
        type: string
      tag_level:
        default: patch
        description: The highest level of tagging to apply.
        options:
          - major
          - minor
          - patch
        required: false
        type: choice
permissions:
  contents: read
  packages: write
jobs:
  dependencies:
    name: Get Dependency Information
    runs-on: ubuntu-latest
    outputs:
      python_digest: ${{ steps.digest.outputs.digest }}
      major_tag: ${{ steps.image_tags.outputs.major_tag }}
      minor_tag: ${{ steps.image_tags.outputs.minor_tag }}
      patch_tag: ${{ steps.image_tags.outputs.patch_tag }}
    steps:
      - name: Get Current Digest for Python 3.10 image
        id: digest
        uses: joepitt91/action-digest-from-dockerhub-image@v1
        with:
          dockerhub_username: ${{ secrets.DOCKER_USER }}
          dockerhub_token: ${{ secrets.DOCKER_PASSWORD }}
          repository: python
          tag: 3.10-slim

      - name: Convert Version to Tags
        id: image_tags
        uses: joepitt91/action-version-to-tags@v1
        with:
          version: ${{ inputs.version }}

  build:
    name: Build Image
    runs-on: ubuntu-latest
    needs:
      - dependencies
    steps:
      - name: Free Up Disk Space
        uses: jlumbroso/free-disk-space@main

      - name: Image Information
        run: echo "Building image of AUTOMATIC1111 ${{ inputs.version }} from python:3.10-slim with digest ${{ needs.dependencies.outputs.python_digest }}"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Image (major)
        if: inputs.tag_level == 'major'
        uses: docker/build-push-action@v6
        with:
          build-args: |
            A1111_VERSION=v${{ inputs.version }}
          provenance: true
          pull: true
          push: true
          sbom: true
          tags: |
            ghcr.io/joepitt91/automatic1111:${{ needs.dependencies.outputs.major_tag }}
            ghcr.io/joepitt91/automatic1111:${{ needs.dependencies.outputs.minor_tag }}
            ghcr.io/joepitt91/automatic1111:${{ needs.dependencies.outputs.patch_tag }}

      - name: Build and Push Image (minor)
        if: inputs.tag_level == 'minor'
        uses: docker/build-push-action@v6
        with:
          build-args: |
            A1111_VERSION=v${{ inputs.version }}
          provenance: true
          pull: true
          push: true
          sbom: true
          tags: |
            ghcr.io/joepitt91/automatic1111:${{ needs.dependencies.outputs.minor_tag }}
            ghcr.io/joepitt91/automatic1111:${{ needs.dependencies.outputs.patch_tag }}

      - name: Build and Push Image (patch)
        if: inputs.tag_level == 'patch'
        uses: docker/build-push-action@v6
        with:
          build-args: |
            A1111_VERSION=v${{ inputs.version }}
          provenance: true
          pull: true
          push: true
          sbom: true
          tags: |
            ghcr.io/joepitt91/automatic1111:${{ needs.dependencies.outputs.patch_tag }}
